import {test,expect} from '@playwright/test';
test('Empty working database → venue → employee → production → calendar → reopen',async({page,request})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');
 await expect(page.getByRole('button',{name:'Создать рабочую базу',exact:true})).toBeVisible();
 await expect(page.getByText('Создать демонстрационный театр',{exact:true})).toHaveCount(0);
 const empty=await (await request.get('/api/bootstrap')).json();expect(empty.resources).toHaveLength(0);expect(empty.productions).toHaveLength(0);
 await page.getByLabel('Название театра',{exact:true}).fill('Рабочий театр');
 await page.getByRole('button',{name:'Создать рабочую базу',exact:true}).click();
 await page.getByRole('button',{name:'Площадки',exact:true}).click();
 await page.getByRole('button',{name:'Добавить площадку',exact:true}).click();
 await page.getByLabel('Название площадки').fill('Рабочая площадка');
 await page.getByRole('button',{name:'Сохранить площадку',exact:true}).click();
 await expect(page.getByLabel('Название площадки')).not.toBeVisible();
 await page.getByRole('button',{name:'Сотрудники',exact:true}).click();
 await page.getByRole('button',{name:'Добавить сотрудника',exact:true}).click();
 await page.getByLabel('Название / ФИО').fill('Новый исполнитель');
 await page.getByLabel('Подразделение',{exact:true}).fill('Артисты');
 await page.getByLabel('Специализация / инструмент').fill('Солист');
 await page.getByRole('dialog').getByRole('button',{name:'Сохранить ресурс',exact:true}).click();
 await expect(page.getByRole('dialog')).not.toBeVisible();
 await page.getByRole('button',{name:'Добавить спектакль',exact:true}).click();
 await page.getByLabel('Название постановки').fill('Моя первая постановка');
 await page.getByRole('button',{name:'Люди',exact:true}).click();
 const roles=page.locator('section').filter({has:page.getByRole('heading',{name:'Роли и составы',exact:true})}).last();
 await roles.getByRole('button',{name:'Добавить пункт',exact:true}).click();
 const b=await (await request.get('/api/bootstrap')).json();const person=b.resources.find((r:any)=>r.kind==='Person');
 await page.getByLabel('Первый состав',{exact:true}).selectOption(String(person.id));
 await page.getByLabel('Второй состав',{exact:true}).selectOption(String(person.id));
 await page.getByLabel('Допущенные исполнители / резерв',{exact:true}).selectOption([String(person.id)]);
 await page.getByRole('button',{name:'Техника',exact:true}).click();
 await page.getByLabel('Звуковой паспорт и сигнальные маршруты').fill('Два радиомикрофона, выходы слева и справа');
 await page.getByRole('button',{name:'Сохранить постановку',exact:true}).click();
 await expect(page.getByLabel('Название постановки')).not.toBeVisible();
 await page.getByRole('button',{name:/^Назначить/}).click();
 await page.getByLabel('Дата',{exact:true}).fill('2026-12-01');
 await page.getByRole('button',{name:'Проверить и назначить',exact:true}).click();
 const preview=page.getByRole('dialog',{name:'Предварительный план'});
 await expect(preview).toBeVisible();await preview.getByRole('button',{name:'Подтвердить',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Календарь',exact:true})).toBeVisible();
 await expect(page.locator('.fc-event').filter({hasText:'Моя первая постановка'})).toBeVisible();
 await page.reload();await page.getByRole('button',{name:'Календарь',exact:true}).click();
 const events=await (await request.get('/api/events')).json();expect(events).toHaveLength(1);
 expect((await request.post('/api/demo')).status()).toBe(404);
 await page.getByRole('button',{name:'Настройки',exact:true}).click();
 await expect(page.getByText('24 демонстрационных конфликта',{exact:true})).toHaveCount(0);
 expect(errors).toEqual([]);
});
