import {apiFetch} from "./NetworkFetch";
import React,{useState,useEffect} from 'react';
import {tr,useLanguage,setLanguage} from './i18n';
import {Connection,connectionApi,ServerIndicator} from './Connection';
type Obj=Record<string,any>;
export async function accountApi(path:string,method='GET',body?:any){
 const response=await apiFetch('/api/auth/'+path,{method,headers:{'Content-Type':'application/json','X-StageOS-Token':sessionStorage.getItem('stageos-token')||''},body:body===undefined?undefined:JSON.stringify(body)});
 const value=await response.json();if(response.status===401&&!['login','session'].includes(path))window.dispatchEvent(new Event('stageos-session-expired'));if(!response.ok)throw Object.assign(Error(typeof value.detail==='string'?value.detail:tr('Проверьте поля формы')),{disconnected:response.headers.get('X-StageOS-Disconnected')==='1' || (!!sessionStorage.getItem('stageos-web-code')&&[502,503,504].includes(response.status))});return value;
}
const roleNames:Obj={admin:'Администратор',artistic_director:'Художественный руководитель',editor:'Планировщик',viewer:'Наблюдатель'};
export function AccountGate({children}:{children:(session:Obj|null,exit:()=>Promise<void>)=>React.ReactNode}){
 const [network,setNetwork]=useState<Obj|null>(null);const [networkOpen,setNetworkOpen]=useState(false);
 useEffect(()=>{const open=()=>{connectionApi().then(n=>{setNetwork(n);setNetworkOpen(true)}).catch(e=>setError(e.message))};window.addEventListener('stageos-connection',open);return ()=>window.removeEventListener('stageos-connection',open)},[]);
 const language=useLanguage();const [ready,setReady]=useState(false);const [enabled,setEnabled]=useState(true);const [session,setSession]=useState<Obj|null>(null);const [theatres,setTheatres]=useState<Obj[]>([]);const [chosen,setChosen]=useState<Obj|null>(null);const [mode,setMode]=useState('choose');const [form,setForm]=useState({theatre_name:'',name:'',login:'',password:''});const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [serverCode,setServerCode]=useState(sessionStorage.getItem('stageos-web-code')||'');
 useEffect(()=>{if(networkOpen&&network?.mode==='web'){setNetworkOpen(false);setSession(null);setMode('server-code');sessionStorage.setItem('stageos-relogin-required','1');}},[networkOpen,network?.mode]);
 const field=(key:string,value:string)=>setForm(f=>({...f,[key]:value}));
 useEffect(()=>{const disconnected=(event:Event)=>{sessionStorage.setItem('stageos-relogin-required','1');setSession(null);setReady(true);setNetworkOpen(false);setChosen(session?.theatre||chosen);setMode((event as CustomEvent).detail?.codeRequired?'server-code':session?.theatre||chosen?'login':'choose');setForm(f=>({...f,login:session?.user.login||f.login,password:''}));setError(tr('Связь с сервером потеряна. Переподключитесь и войдите снова.'));};window.addEventListener('stageos-server-disconnected',disconnected);return()=>window.removeEventListener('stageos-server-disconnected',disconnected)},[session,chosen]);
 useEffect(()=>{if(!session||!['client','web'].includes(network?.mode))return;let active=true,pending=false;const poll=async()=>{if(pending||document.hidden)return;pending=true;try{await accountApi('session')}catch(e:any){if(active && !e.disconnected && !e.transient){if(e instanceof TypeError)window.dispatchEvent(new Event('stageos-server-disconnected'));else window.dispatchEvent(new Event('stageos-session-expired'));}}finally{pending=false}};const timer=setInterval(poll,30000);return()=>{active=false;clearInterval(timer)}},[session,network?.mode]);
 async function refresh(){const r=await accountApi('theatres');setEnabled(r.enabled);setTheatres(r.theatres);return r;}
 useEffect(()=>{const expired=()=>{setSession(null);setChosen(null);setMode('choose');setForm(f=>({...f,password:''}));setError(tr('Сеанс завершён. Войдите снова.'));};window.addEventListener('stageos-session-expired',expired);return ()=>window.removeEventListener('stageos-session-expired',expired)},[]);
 useEffect(()=>{(async()=>{try{const n=await connectionApi();setNetwork(n);if(n?.mode==='web'&&!sessionStorage.getItem('stageos-web-code')){setMode('server-code');setReady(true);return;}const r=await refresh();if(r.enabled&&!sessionStorage.getItem('stageos-relogin-required')){try{setSession(await accountApi('session'))}catch{}}setReady(true)}catch(e:any){setError(e.message)}})()},[]);
 async function exit(){await accountApi('logout','POST');setSession(null);setChosen(null);setForm({theatre_name:'',name:'',login:'',password:''});setMode('choose');setError('');await refresh();}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{
  if(mode==='server-code'){sessionStorage.setItem('stageos-web-code',serverCode.trim());await refresh();setMode('choose');setReady(true);}
  else if(mode==='create'){const t=await accountApi('theatres','POST',form);await refresh();setChosen(t);setMode('login');setForm(f=>({...f,password:''}));}
  else if(mode==='setup'){await accountApi('theatres/'+chosen!.id+'/setup','POST',{...form,role:'admin'});await refresh();setMode('login');setForm(f=>({...f,password:''}));}
  else {setSession(await accountApi('login','POST',{theatre_id:chosen!.id,login:form.login,password:form.password}));sessionStorage.removeItem('stageos-relogin-required');setForm(f=>({...f,password:''}));}
 }catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(networkOpen&&network&&network.mode!=='web')return <div className="account-gate"><Connection initial={network} onClose={()=>setNetworkOpen(false)}/></div>;
 if(ready&&(!enabled||session))return <>{children(enabled?session:null,exit)}{enabled&&<ServerIndicator/>}</>;
 return <div className="account-gate"><div className="account-brand"><img src="/stageos-icon.svg" width="52" height="52" alt=""/><strong>StageOS</strong><span>{tr('Театральное производство')}</span><select aria-label={tr('Язык приложения')} value={language} onChange={e=>setLanguage(e.target.value as 'ru'|'en')}><option value="ru">Русский</option><option value="en">English</option></select></div><section className={'account-panel '+(mode==='choose'?'account-choose':'')}>
 <span className="eyebrow">{tr(['client','web'].includes(network?.mode)?'Общее пространство сервера':'Локальные пространства')}</span><h1>{tr(mode==='server-code'?'Подключение через браузер':mode==='choose'?'Выберите театр':mode==='create'?'Создать свой театр':mode==='setup'?'Настроить вход':'Вход в аккаунт')}</h1>
 {error&&<p role="alert" className="error-banner">{tr(error)}</p>}
 {network&&mode!=='server-code'&&<button onClick={()=>setNetworkOpen(true)}>{tr('Настроить подключение')}</button>}
 {!ready?<p>{tr('Подключение к локальному ядру…')}<button onClick={()=>location.reload()}>{tr('Повторить')}</button></p>:mode==='server-code'?<form onSubmit={submit}><p>{tr('Введите код подключения, который показан в окне StageOS Server. Затем выберите театр и войдите личным логином и паролем.')}</p><label className="field"><span>{tr('Код подключения')}</span><input type="password" required minLength={8} maxLength={128} autoComplete="off" value={serverCode} onChange={e=>setServerCode(e.target.value)}/></label><button className="primary" disabled={busy}>{tr('Проверить код и продолжить')}</button></form>:mode==='choose'?<>
 <p className="muted">{tr('У каждого театра своя база, сотрудники и расписание.')}</p><div className="theatre-choices">{theatres.map(t=><button key={t.id} onClick={()=>{setChosen(t);setMode(t.needs_setup?'setup':'login');setError('');}}><span className="avatar">{t.name.slice(0,1)}</span><span><strong>{t.name}</strong><small>{tr(t.needs_setup?'Первый вход: настройте администратора':'Войти по логину и паролю')}</small></span><span>→</span></button>)}</div>
 {!theatres.length&&<p className="empty">{tr('Театров пока нет. Создайте первое пространство.')}</p>}{!['client','web'].includes(network?.mode)&&<button className="primary" onClick={()=>{setMode('create');setForm({theatre_name:'',name:'',login:'',password:''});}}>{tr('Создать свой театр')}</button>}
 </>:<form onSubmit={submit}>{chosen&&<p className="account-theatre">{chosen.name}</p>}{mode==='setup'&&<p className="muted">{tr('Существующая база сохранена. Создайте администратора для входа.')}</p>}
 {mode==='create'&&<label className="field"><span>{tr('Название театра')}</span><input autoFocus required maxLength={200} value={form.theatre_name} onChange={e=>field('theatre_name',e.target.value)}/></label>}
 {mode!=='login'&&<label className="field"><span>{tr('Имя администратора')}</span><input required maxLength={120} value={form.name} onChange={e=>field('name',e.target.value)}/></label>}
 <label className="field"><span>{tr('Логин')}</span><input autoFocus={mode==='login'} autoComplete="username" required maxLength={120} value={form.login} onChange={e=>field('login',e.target.value)}/></label>
 <label className="field"><span>{tr('Пароль')}</span><input type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='login'?1:6} maxLength={256} value={form.password} onChange={e=>field('password',e.target.value)}/></label>
 <button className="primary" disabled={busy}>{tr(busy?'Подождите…':mode==='login'?'Войти':mode==='create'?'Создать театр':'Сохранить администратора')}</button><button type="button" onClick={()=>{setMode('choose');setForm(f=>({...f,password:''}));setError('')}}>{tr('Назад к театрам')}</button>
 </form>}
 </section><p className="account-footer">{tr(network?.mode==='client'?'Данные хранятся на компьютере сервера.':'Ваши данные остаются на этом компьютере.')}</p></div>;
}
export function AccountMenu({session,exit}:{session:Obj;exit:()=>Promise<void>}){
 const [open,setOpen]=useState(false);const [manage,setManage]=useState(false);const [users,setUsers]=useState<Obj[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [form,setForm]=useState({name:'',login:'',password:'',role:'viewer'});const [password,setPassword]=useState({current_password:'',password:''});const [change,setChange]=useState(false);const [reset,setReset]=useState<Obj|null>(null);const [newPassword,setNewPassword]=useState('');
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const load=async()=>setUsers(await accountApi('users'));
 return <div className="account-menu"><button className="account-person" onClick={()=>setOpen(!open)} aria-label={tr('Личный аккаунт')}><span className="avatar">{session.user.name.slice(0,1)}</span><span>{session.user.name}<small>{tr(roleNames[session.user.role])}</small></span></button>{open&&<div className="account-dropdown"><strong>{session.theatre.name}</strong><button onClick={()=>{setOpen(false);window.dispatchEvent(new Event('stageos-connection'))}}>{tr('Подключение к серверу')}</button>{session.user.role==='admin'&&<button onClick={()=>run(async()=>{await load();setManage(true);setOpen(false)})}>{tr('Пользователи и роли')}</button>}<button onClick={()=>{setChange(true);setOpen(false)}}>{tr('Изменить пароль')}</button><button disabled={busy} onClick={()=>run(exit)}>{tr('Выйти из аккаунта')}</button><button disabled={busy} onClick={()=>run(exit)}>{tr('Переключить театр')}</button></div>}
 {error&&!manage&&!change&&<p role="alert">{tr(error)}</p>}
 {(manage||change)&&<div className="overlay"><section className="modal account-admin" role="dialog" aria-modal="true" aria-label={tr(manage?'Пользователи и роли':'Изменить пароль')}><div className="row between"><h2>{tr(manage?'Пользователи и роли':'Изменить пароль')}</h2><button onClick={()=>{setManage(false);setChange(false);setReset(null);setNewPassword('');setError('')}}>{tr('Закрыть')}</button></div>{error&&<p role="alert" className="error-banner">{tr(error)}</p>}
 {manage?<><p className="muted">{tr('Администратор: все права. Художественный руководитель: назначение спектаклей и согласование конфликтов. Планировщик: полное составление постановок и расписания; серьёзные конфликты — через согласование. Наблюдатель: просмотр.')}</p><div className="account-users">{users.map(u=><div key={u.id}><span><strong>{u.name}</strong><small>{u.login}</small></span><select aria-label={tr('Роль')+' '+u.name} value={u.role} disabled={busy} onChange={e=>run(async()=>{await accountApi('users/'+u.id,'PATCH',{role:e.target.value});await load()})}>{Object.entries(roleNames).map(([k,v])=><option key={k} value={k}>{tr(v as string)}</option>)}</select><button disabled={busy} onClick={()=>run(async()=>{await accountApi('users/'+u.id,'PATCH',{active:!u.active});await load()})}>{tr(u.active?'Отключить':'Включить')}</button><button disabled={busy} onClick={()=>{setReset(u);setNewPassword('')}}>{tr('Сбросить пароль')}</button></div>)}</div>
 {reset&&<form onSubmit={e=>{e.preventDefault();run(async()=>{await accountApi('users/'+reset.id,'PATCH',{password:newPassword});setReset(null);setNewPassword('');await load()})}}><h3>{tr('Новый пароль')} · {reset.name}</h3><label className="field"><span>{tr('Новый пароль')}</span><input type="password" required minLength={6} maxLength={256} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><button disabled={busy}>{tr('Сохранить пароль')}</button></form>}
 <form onSubmit={e=>{e.preventDefault();run(async()=>{await accountApi('users','POST',form);setForm({name:'',login:'',password:'',role:'viewer'});await load()})}}><h3>{tr('Добавить пользователя')}</h3>{[['name','Имя пользователя'],['login','Логин'],['password','Пароль']].map(([key,label])=><label className="field" key={key}><span>{tr(label)}</span><input type={key==='password'?'password':'text'} required minLength={key==='password'?6:2} maxLength={key==='password'?256:120} value={(form as Obj)[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label className="field"><span>{tr('Роль')}</span><select aria-label={tr("Роль")} value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{Object.entries(roleNames).map(([k,v])=><option key={k} value={k}>{tr(v as string)}</option>)}</select></label><button className="primary" disabled={busy}>{tr('Создать пользователя')}</button></form></>:<form onSubmit={e=>{e.preventDefault();run(async()=>{await accountApi('password','POST',password);await exit()})}}><label className="field"><span>{tr('Текущий пароль')}</span><input type="password" required value={password.current_password} onChange={e=>setPassword({...password,current_password:e.target.value})}/></label><label className="field"><span>{tr('Новый пароль')}</span><input type="password" required minLength={6} maxLength={256} value={password.password} onChange={e=>setPassword({...password,password:e.target.value})}/></label><button disabled={busy} className="primary">{tr('Сохранить пароль и выйти')}</button></form>}
 </section></div>}
 </div>;
}
