import React,{useState} from 'react';
import {tr} from './i18n';
type Obj=Record<string,any>;
export async function connectionApi(method='GET',body?:Obj){
 const r=await fetch('/api/connection',{method,headers:{'Content-Type':'application/json','X-StageOS-Token':sessionStorage.getItem('stageos-token')||''},body:body?JSON.stringify(body):undefined});
 if(r.status===404)return null;
 const value=await r.json();if(!r.ok)throw Error(typeof value.detail==='string'?value.detail:tr('Проверьте настройки подключения'));return value;
}
export function Connection({initial,onClose}:{initial:Obj,onClose:()=>void}){
 const [state,setState]=useState(initial),[mode,setMode]=useState(initial.mode),[address,setAddress]=useState(initial.address||''),[code,setCode]=useState(initial.mode==='client'?initial.code:''),[port,setPort]=useState(String(initial.port||8765)),[changed,setChanged]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function apply(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await connectionApi('POST',{mode,address,code,port:Number(port)});setState(result);setChanged(true);if(mode==='server'){setMode('server')}else location.reload()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="account-panel connection-panel"><span className="eyebrow">StageOS Server</span><h1>{tr('Подключение к общей базе')}</h1><p className="muted">{tr('Одна база на сервере. Все компьютеры работают с актуальными данными.')}</p>
 <div className="connection-options">{[['local','Только этот компьютер'],['server','Сервер на этом компьютере'],['client','Подключиться к серверу']].map(([key,label])=><button key={key} className={mode===key?'active':''} onClick={()=>setMode(key)}>{tr(label)}</button>)}</div>
 {error&&<p role="alert" className="error-banner">{tr(error)}</p>}{state.error&&<p role="alert" className="error-banner">{state.error}</p>}
 <form onSubmit={apply}>{mode==='client'&&<><label className="field"><span>{tr('Адрес сервера')}</span><input required placeholder="192.168.1.10:8765" value={address} onChange={e=>setAddress(e.target.value)}/></label><label className="field"><span>{tr('Код подключения')}</span><input required autoComplete="off" value={code} onChange={e=>setCode(e.target.value)}/></label><p className="muted">{tr('Получите адрес и код у администратора. Затем войдите своим логином и паролем.')}</p></>}
 {mode==='server'&&<><label className="field"><span>{tr('Порт сервера')}</span><input type="number" required min={1024} max={65535} value={port} onChange={e=>setPort(e.target.value)}/></label>{state.running&&<><button type="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch('/api/connection/firewall',{method:'POST',headers:{'X-StageOS-Token':sessionStorage.getItem('stageos-token')||''}});const v=await r.json();if(!r.ok)throw Error(v.detail);setError(v.message)}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>{tr('Разрешить подключения в Windows')}</button><div className="connection-receipt"><strong>{tr('Сервер работает')}</strong><p>{tr('Адреса подключения')}:</p>{state.addresses.map((a:string)=><code key={a}>{a}</code>)}<p>{tr('Код подключения')}:</p><code>{state.code}</code><p className="muted">{tr('Передайте адрес и код сотрудникам. Для удалённых компьютеров используйте адрес локальной сети, не 127.0.0.1.')}</p></div></>}<p className="muted">{tr('Разрешите входящие подключения в брандмауэре для частной сети. Сервер работает, пока приложение открыто и компьютер не спит.')}</p><p className="muted">{tr('Для доступа через интернет нужен защищённый HTTPS-адрес или VPN. Не открывайте этот HTTP-порт напрямую в интернет.')}</p></>}
 {mode==='local'&&<p className="muted">{tr('Локальная база сохранена. Другие компьютеры не подключаются.')}</p>}
 <button className="primary" disabled={busy}>{tr(busy?'Подождите…':mode==='server'?'Запустить сервер':mode==='client'?'Проверить и подключиться':'Использовать локальную базу')}</button><button type="button" disabled={busy} onClick={()=>changed?location.reload():onClose()}>{tr('Продолжить')}</button></form></section>;
}
