import {getLanguage,tr,message} from "./i18n";
const dictionary: Record<string, string> = {
  Preview: "Предварительный план",
  "Stage Assistant": "Помощник StageOS",
  Custom: "Другой сервер",
  Cast: "Состав",
  IEM: "Персональный мониторинг",
  LED: "Светодиоды",
  SDI: "Видеосигнал",
  DMX: "Управление светом",
  RF: "Радиочастоты",
  flying: "Подвесной",
  Engine: "движок",
  Person: "Сотрудник",
  Venue: "Площадка",
  Room: "Помещение",
  Equipment: "Оборудование",
  "Equipment Kit": "Комплект оборудования",
  Vehicle: "Транспорт",
  Scenery: "Декорация",
  Prop: "Реквизит",
  Costume: "Костюм",
  "Fly Bar": "Штанкет",
  Soffit: "Софит",
  "Lighting Position": "Световая позиция",
  READY: "Готово",
  WARNING: "Предупреждение",
  CONFLICT: "Конфликт",
  ERROR: "Ошибка",
  CRITICAL: "Критический",
  INFO: "Информация",
  Draft: "Черновик",
  Planning: "Планирование",
  "Pending Approval": "На согласовании",
  Approved: "Согласовано",
  Rejected: "Отклонено",
  "In Preparation": "Подготовка",
  Ready: "Готово",
  "In Progress": "В работе",
  Completed: "Завершено",
  Cancelled: "Отменено",
  PROPOSED: "Предложение",
  PLANNED: "План",
  ACTUAL: "Факт",
  available: "Доступно",
  reserved: "Зарезервировано",
  in_use: "Используется",
  in_transit: "В пути",
  maintenance: "Обслуживание",
  broken: "Неисправно",
  limited_use: "Ограниченное использование",
  absence: "Отсутствие",
  "FULL VERSION": "Полная версия",
  "REDUCED VERSION": "Сокращённая версия",
  "TOURING VERSION": "Выездная версия",
  INCOMPATIBLE: "Несовместимо",
  REHEARSAL: "Репетиция",
  Full: "Полный",
  Reduced: "Сокращённый",
  Touring: "Выездной",
  "Technical Check": "Техническая проверка",
  "Orchestra setup": "Подготовка оркестра",
  "RF check": "Проверка радиочастот",
  OPTIMAL: "Оптимальный план",
  FEASIBLE: "Допустимый план",
  INFEASIBLE: "Нет допустимого плана",
  UNKNOWN: "Не определено",
  OK: "Исправно",
  Disabled: "Отключено",
  Connected: "Подключено",
  Configured: "Настроено",
  venue_id: "Площадка",
  capacity: "Допустимая нагрузка / вместимость",
  current_load: "Текущая нагрузка",
  movement: "Движение",
  scenery_allowed: "Подвес декораций разрешён",
  lighting_allowed: "Размещение света разрешено",
  retired: "Выведено из эксплуатации",
  width: "Ширина",
  height: "Высота",
  depth: "Глубина",
  mass: "Масса",
  power: "Мощность",
  dmx: "Световые линии",
  "DMX universes": "Световые линии",
  orchestra: "Места оркестра",
  fly_system: "Верхняя механика",
  bar_load: "Нагрузка штанкета",
  gate_width: "Ширина ворот",
  gate_height: "Высота ворот",
  travel: "Переезд, мин",
  soffits: "Софиты",
  fly_bars: "Штанкеты",
  lighting_positions: "Световые позиции",
  pa: "Звуковая система",
  video: "Видео",
  rooms: "Гримёрные",
  opening: "Открытие",
  closing: "Закрытие",
  seats: "Места в зале",
  qualification: "Квалификация",
  specialization: "Специализация",
  level: "Разряд",
  protocol: "Протокол",
  category: "Категория",
  item_name: "Наименование позиции",
  quantity: "Количество",
  items: "Состав комплекта",
  critical: "Обязательный",
  setup: "Монтаж, мин",
  crew: "Специалисты",
  fly: "Подвес",
  installation: "Тип установки",
  floor: "Напольный",
  flown: "Подвесной",
  true: "Да",
  false: "Нет",
  reserve: "Резерв",
  load: "Погрузка",
  unload: "Разгрузка",
  stage: "Сцена",
  lighting: "Свет",
  sound: "Звук",
  rf: "Радиочастоты",
  check: "Проверка",
  teardown: "Демонтаж",
  preferred_soffits: "Предпочтительно софитов",
  moving_fly_bars: "Подвижные штанкеты",
  Database: "База данных",
  "Production Engine": "План производства",
  "Calendar Engine": "Календарь",
  "Venue Compatibility": "Совместимость площадки",
  "Stage Mechanics": "Сценическая механика",
  "Lighting Infrastructure": "Световая инфраструктура",
  "Resource Engine": "Учёт ресурсов",
  "Conflict Engine": "Проверка конфликтов",
  "Scheduling Engine": "Планировщик",
  "Local AI": "Локальный помощник",
  "OR-Tools": "Решатель ограничений",
};
const words: Record<string, string> = {
  "Violin I": "Первые скрипки",
  "Violin II": "Вторые скрипки",
  Viola: "Альты",
  Cello: "Виолончели",
  "Double Bass": "Контрабасы",
  Flute: "Флейты",
  Oboe: "Гобой",
  Clarinet: "Кларнет",
  Bassoon: "Фагот",
  Horn: "Валторна",
  Trumpet: "Труба",
  Trombone: "Тромбон",
  Tuba: "Туба",
  Percussion: "Ударные",
  Harp: "Арфа",
  Keyboard: "Клавишные",
  Soprano: "Сопрано",
  Alto: "Альт",
  Tenor: "Тенор",
  Bass: "Бас",
  Principal: "Ведущий артист",
  Soloist: "Солист",
  Ensemble: "Ансамбль",
  Reserve: "Резерв",
  Rigging: "Подвесы",
  "Media Server": "Медиасервер",
  "Moving Head": "Поворотный прибор",
  Followspot: "Следящий прожектор",
  Microphone: "Микрофон",
  Wireless: "Радиосистема",
  Stagebox: "Сценический блок",
  Console: "Консоль",
  Projector: "Проектор",
  Camera: "Камера",
  Platform: "Платформа",
  Stand: "Стойка",
  Hoist: "Лебёдка",
  Sling: "Строп",
  Profile: "Профильный прожектор",
  Wash: "Заливной свет",
  "LED Bar": "Светодиодная линейка",
  haze: "Дымка",
  fog: "Дым",
  Kit: "Комплект",
  Sound: "Звук",
  Light: "Свет",
  Video: "Видео",
};
export function ru(value: any): string {
  if (value === null || value === undefined) return "—";
  const s = String(value);
  if (getLanguage()==="en") {
    if (dictionary[s]) return tr(dictionary[s])===dictionary[s] ? s.replaceAll("_"," ") : tr(dictionary[s]);
    return message(s);
  }
  if (dictionary[s]) return dictionary[s];
  let out = s;
  for (const [a, b] of Object.entries({ ...words, ...dictionary }).sort(
    (a, b) => b[0].length - a[0].length,
  )) {
    out = out.replace(
      new RegExp(
        "(?<![A-Za-z_])" +
          a.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") +
          "(?![A-Za-z_])",
        "g",
      ),
      b,
    );
  }
  return out;
}
