import {apiFetch} from "./NetworkFetch";
import React,{useState} from 'react';
import {tr} from './i18n';
type Obj=Record<string,any>;
export function Tunnel({state,onUpdate}:{state:Obj,onUpdate:(s:Obj)=>void}){
 const [token,setToken]=useState(''),[remember,setRemember]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false),[protocol,setProtocol]=useState('http2');
 const t=state.tunnel||{},provider=t.provider||'ngrok',cloudflare=provider==='cloudflare';
 const labels:Obj={stopped:'Интернет-туннель остановлен',installing:cloudflare?'Загрузка Cloudflare…':'Загрузка ngrok…',starting:'Проверяем внешний адрес…',connected:'Интернет-туннель подключён',disconnected:'Нет связи через интернет-туннель',error:'Ошибка интернет-туннеля'};
 async function action(action:string,extra:Obj={}){setBusy(true);setError('');setCopied(false);const submitted=action==='start'?token:'';if(action==='start'||action==='select')setToken('');try{
  const r=await apiFetch('/api/connection/tunnel',{method:'POST',headers:{'Content-Type':'application/json','X-StageOS-Token':sessionStorage.getItem('stageos-token')||''},body:JSON.stringify({action,...extra,...(action==='start'?(cloudflare?{protocol}:{authtoken:submitted,remember}):{})})});
  const value=await r.json();if(!r.ok)throw Error(typeof value.detail==='string'?value.detail:'Проверьте настройки подключения');onUpdate(value);
 }catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function copy(){try{await navigator.clipboard.writeText(t.url);setCopied(true)}catch{setError(tr('Не удалось скопировать. Выделите адрес и скопируйте вручную.'))}}
 const allowed=state.can_manage_tunnel&&!busy&&state.running;
 const active=['starting','connected','disconnected'].includes(t.phase);
 return <div className="server-tunnel"><h3>{tr('Доступ через Интернет')}</h3>
 <label className="field"><span>{tr('Сервис туннеля')}</span><select aria-label={tr('Сервис туннеля')} value={provider} disabled={!allowed||active} onChange={e=>action('select',{provider:e.target.value})}><option value="cloudflare">Cloudflare Quick Tunnel</option><option value="ngrok">ngrok</option></select></label>
 {cloudflare?<><p>{tr('Бесплатный туннель Cloudflare. Аккаунт, домен и ключ не нужны. База остаётся на компьютере сервера.')}</p><p className="notice">{tr('Ссылка остаётся одной, пока этот туннель работает. После нового запуска адрес изменится — отправьте пользователям новую ссылку.')}</p><p className="muted">{tr('Доступ без VPN проверьте с телефона через мобильный интернет. Проверка сервера не подтверждает доступность из всех сетей.')}</p></>:<><p>{tr('ngrok выступает посредником между клиентами и вашим ПК. База остаётся на компьютере сервера. Нужен аккаунт ngrok и его Authtoken.')}</p><p><a href="https://dashboard.ngrok.com/get-started/your-authtoken" target="_blank" rel="noreferrer">{tr('Открыть аккаунт ngrok')}</a></p></>}
 <strong role="status">{tr(labels[t.phase]||labels.stopped)}</strong>
 {t.checked_at&&<small className="server-checked">{tr('Последняя проверка')}: {new Date(t.checked_at).toLocaleTimeString()}</small>}
 {t.error&&<p className="server-warning">{tr(t.error)}</p>}{error&&<p role="alert" className="error-banner">{tr(error)}</p>}
 {!state.can_manage_tunnel&&<p className="muted">{tr('Управление туннелем: войдите администратором на компьютере сервера.')}</p>}
 {!t.installed?<><p className="muted">{tr(cloudflare?'Кнопка загрузит проверенный cloudflared с официального GitHub. Установка выполняется один раз.':'Кнопка загрузит проверенную версию ngrok с официального сайта. Установка выполняется один раз.')}</p><button type="button" disabled={!allowed||!t.can_install} onClick={()=>action('install')}>{tr(busy?(cloudflare?'Загрузка Cloudflare…':'Загрузка ngrok…'):(cloudflare?'Установить Cloudflare':'Установить ngrok'))}</button></>:<>
 {cloudflare?<label className="field"><span>{tr('Способ соединения')}</span><select aria-label={tr('Способ соединения')} value={protocol} disabled={!allowed||active} onChange={e=>setProtocol(e.target.value)}><option value="http2">{tr('Совместимый (HTTP/2)')}</option><option value="auto">{tr('Автоматический')}</option><option value="quic">QUIC</option></select><small>{tr('Совместимый режим использует TCP. Если соединение не устанавливается, попробуйте автоматический режим.')}</small></label>:<><label className="field"><span>{tr('Authtoken ngrok')}</span><input type="password" autoComplete="new-password" spellCheck={false} value={token} disabled={!allowed||active} onChange={e=>setToken(e.target.value)} placeholder={tr(t.saved_key?'Сохранённый ключ будет использован':'Вставьте ключ из аккаунта ngrok')}/></label><label className="tunnel-remember"><input type="checkbox" checked={remember} disabled={!allowed||active||!state.windows} onChange={e=>setRemember(e.target.checked)}/><span>{tr('Сохранить ключ в Windows для текущего пользователя')}</span></label></>}
 <div className="server-actions"><button type="button" disabled={!allowed||active||(!cloudflare&&!token&&!t.saved_key)} onClick={()=>action('start')}>{tr(busy?'Выполняем…':'Запустить интернет-туннель')}</button><button type="button" disabled={!allowed||t.phase==='stopped'} onClick={()=>action('stop')}>{tr('Остановить туннель')}</button>{!cloudflare&&t.saved_key&&<button type="button" disabled={!allowed} onClick={()=>action('forget')}>{tr('Удалить сохранённый ключ')}</button>}</div>
 </>}
 {t.verified&&t.phase==='connected'&&t.url&&<div className="connection-receipt"><strong>{tr('Проверенный внешний адрес')}</strong><code>{t.url}</code><button type="button" onClick={copy}>{tr(copied?'Адрес скопирован':'Скопировать адрес')}</button><p>{tr('Для телефона откройте этот адрес в Safari и войдите личным логином и паролем. Для полного интерфейса на ПК также потребуется код подключения сервера.')}</p></div>}
 <p className="muted">{tr(cloudflare?'Сервер и ПК должны оставаться включёнными. Cloudflare Quick Tunnel не гарантирует постоянную доступность; при новом запуске ссылка меняется.':'После перезапуска приложения запустите туннель снова. Сервер и ПК должны оставаться включёнными. Доступность и лимиты зависят от аккаунта ngrok.')}</p>
 </div>;
}
